version: '3.8'
services:
  mongo:
    image: mongo:4.4.6
    volumes:
      - vol-db:/data/db
  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_URL=mongodb://mongo:27017
volumes:
  vol-db: